
import java.io.IOException;
import java.net.HttpURLConnection;
import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.awt.event.*;
import java.io.ByteArrayOutputStream;
import java.io.InputStream;
import java.io.PrintStream;
import java.util.Scanner;
import javax.swing.JOptionPane;


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author samuel
 */
public class Clientserverconnect extends javax.swing.JFrame {

    /**
     * Creates new form Clientserverconnect
     */
    public Clientserverconnect() {
        initComponents();
        String PN;
        String CN;
        
        //Using DAO class to store values
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Photo = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Go = new javax.swing.JButton();
        CN = new javax.swing.JTextField();
        PN = new javax.swing.JTextField();
        CLS = new javax.swing.JButton();
        RTN = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Photo.setBackground(new java.awt.Color(51, 0, 51));

        javax.swing.GroupLayout PhotoLayout = new javax.swing.GroupLayout(Photo);
        Photo.setLayout(PhotoLayout);
        PhotoLayout.setHorizontalGroup(
            PhotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );
        PhotoLayout.setVerticalGroup(
            PhotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        getContentPane().add(Photo, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 0, 200, 140));

        jLabel1.setBackground(new java.awt.Color(204, 204, 204));
        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel1.setText("Client_Name");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 120, 30));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel2.setText("Photographer_Name");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 130, 30));

        Go.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        Go.setText("GO");
        Go.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GoActionPerformed(evt);
            }
        });
        getContentPane().add(Go, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 250, 90, 30));

        CN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CNActionPerformed(evt);
            }
        });
        getContentPane().add(CN, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 150, 160, 30));

        PN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PNActionPerformed(evt);
            }
        });
        getContentPane().add(PN, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 200, 160, 30));

        CLS.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        CLS.setText("CLS");
        CLS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CLSActionPerformed(evt);
            }
        });
        getContentPane().add(CLS, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 250, -1, 30));

        RTN.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        RTN.setText("Return");
        RTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RTNActionPerformed(evt);
            }
        });
        getContentPane().add(RTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 290, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

      public static String getdata(String name) throws IOException
        {
		HttpURLConnection connection = (HttpURLConnection) new URL("http://localhost:8090/WebPhotos2/Photoservlet" + name).openConnection();
		
		connection.setRequestMethod("GET");

		int responseCode = connection.getResponseCode();
		if(responseCode == 200){
			String response = "";
			Scanner scanner = new Scanner(connection.getInputStream());
			while(scanner.hasNextLine()){
				response += scanner.nextLine();
				response += "\n";
			}
			scanner.close();

			return response;
                       // System.out.println(response);
		}
		  //System.out.println(response);
		// an error happened
		return null;
	}
    private void CNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CNActionPerformed
      
        
    }//GEN-LAST:event_CNActionPerformed

    private void CLSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CLSActionPerformed
        // TODO add your handling code here:
     //   String CName = CN.getText().toString();
   CN.setText(null);
   PN.setText(null);
        
    }//GEN-LAST:event_CLSActionPerformed

    private void GoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GoActionPerformed
String ID=CN.getText().toString();
String PH=PN.getText().toString();
if(ID.equals("")){
JOptionPane.showMessageDialog(null, "Field is Mandatory");
}
if(PH.equals("")){
JOptionPane.showMessageDialog(null, "Field is Mandatory");
}

//System.out.println("Client Name is: " + ID);

//System.out.println("Photographer Name is: " +PH);
// TODO add your handling code here:  
    }//GEN-LAST:event_GoActionPerformed

    private void PNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PNActionPerformed

    private void RTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RTNActionPerformed
        try {
            String response = getdata("");
            
            System.out.println(response);
            
            
            String ID=CN.getText().toString();
            String PH=PN.getText().toString();
            
// Create a stream to hold the output
//Scanner cs=new Scanner(System.in);{
ByteArrayOutputStream baos = new ByteArrayOutputStream();
PrintStream ps = new PrintStream(baos);
// IMPORTANT: Save the old System.out!
PrintStream old = System.out;
// Tell Java to use your special stream
System.setOut(ps);
// Print some output: goes to your special stream
System.out.println(ID);
System.out.println(PH);
// Put things back
System.out.flush();
System.setOut(old);

// Show what happened
CN.setText(ID);
//PN.setText(PH);
//System.in();
CN.setText(baos.toString());
//PN.setText(baos.toString());
// TODO add your handling code here:
//cs.setText(baos.toString());
        } catch (IOException ex) {
            Logger.getLogger(Clientserverconnect.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_RTNActionPerformed

/**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Clientserverconnect.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Clientserverconnect.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Clientserverconnect.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Clientserverconnect.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Clientserverconnect().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CLS;
    private javax.swing.JTextField CN;
    private javax.swing.JButton Go;
    private javax.swing.JTextField PN;
    private javax.swing.JPanel Photo;
    private javax.swing.JButton RTN;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables

}
